/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AdvancedType,
  SlideValue,
} from './components/demo-component/demo-component';

export namespace Components {
  interface AccordionContainer {
    'heading': string;
  }
  interface AccordionItem {
    'content': string;
    'heading': string;
  }
  interface DemoComponent {
    'advanced': AdvancedType;
    'max': number;
    'min': number;
    'value'?: string | null;
  }
}

declare global {


  interface HTMLAccordionContainerElement extends Components.AccordionContainer, HTMLStencilElement {}
  var HTMLAccordionContainerElement: {
    prototype: HTMLAccordionContainerElement;
    new (): HTMLAccordionContainerElement;
  };

  interface HTMLAccordionItemElement extends Components.AccordionItem, HTMLStencilElement {}
  var HTMLAccordionItemElement: {
    prototype: HTMLAccordionItemElement;
    new (): HTMLAccordionItemElement;
  };

  interface HTMLDemoComponentElement extends Components.DemoComponent, HTMLStencilElement {}
  var HTMLDemoComponentElement: {
    prototype: HTMLDemoComponentElement;
    new (): HTMLDemoComponentElement;
  };
  interface HTMLElementTagNameMap {
    'accordion-container': HTMLAccordionContainerElement;
    'accordion-item': HTMLAccordionItemElement;
    'demo-component': HTMLDemoComponentElement;
  }
}

declare namespace LocalJSX {
  interface AccordionContainer {
    'heading'?: string;
  }
  interface AccordionItem {
    'content'?: string;
    'heading'?: string;
  }
  interface DemoComponent {
    'advanced'?: AdvancedType;
    'max'?: number;
    'min'?: number;
    'onSlideChanged'?: (event: CustomEvent<SlideValue>) => void;
    'value'?: string | null;
  }

  interface IntrinsicElements {
    'accordion-container': AccordionContainer;
    'accordion-item': AccordionItem;
    'demo-component': DemoComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'accordion-container': LocalJSX.AccordionContainer & JSXBase.HTMLAttributes<HTMLAccordionContainerElement>;
      'accordion-item': LocalJSX.AccordionItem & JSXBase.HTMLAttributes<HTMLAccordionItemElement>;
      'demo-component': LocalJSX.DemoComponent & JSXBase.HTMLAttributes<HTMLDemoComponentElement>;
    }
  }
}


